const data = [
    {
      id: 1,
      title: 'Fire catches in a car',
      location: 'Main road, Sant Nagar',
      distance: '500mt',
      upvotes: '10k',
      downvotes: '200k',
      comments: '10k',
      shares: '20k',
      time: '10m',
    },
    {
      id: 2,
      title: 'Building collapse',
      location: 'Sector 21, Noida',
      distance: '1.2km',
      upvotes: '15k',
      downvotes: '500',
      comments: '5k',
      shares: '8k',
      time: '15m',
    },
    {
      id: 3,
      title: 'Traffic Jam',
      location: 'Ring Road, Delhi',
      distance: '2.3km',
      upvotes: '8k',
      downvotes: '100',
      comments: '3k',
      shares: '5k',
      time: '20m',
    },
    {
      id: 4,
      title: 'Waterlogging on roads',
      location: 'MG Road, Gurgaon',
      distance: '400mt',
      upvotes: '12k',
      downvotes: '1k',
      comments: '7k',
      shares: '10k',
      time: '25m',
    },
  ];
  module.exports = data;